version 6.0
syntax on
set autoindent
set backspace=indent,eol,start
set backup
set diffexpr=MyDiff()
set helplang=En
set history=50
set hlsearch
set incsearch
set keymodel=startsel,stopsel
set ruler
set selection=exclusive
set selectmode=mouse,key
set whichwrap=b,s,<,>,[,]
" vim: set ft=vim :
" Windows only: set shell=D:/cygwin/bin/bash.exe
set tabstop=4
set shiftwidth=4
set textwidth=72
filetype plugin indent on
set guifont=Consolas:h10:cANSI
set lines=35 columns=147

" Solarized dark
syntax enable
set background=dark
colorscheme solarized

" Load pathogen
execute pathogen#infect()

